# it is important to use this apiVersion
apiVersion: witboost.com/v2
kind: EditTemplate
metadata:
  name: edit-bigquery-storage-template.1
  title: Google BigQuery Storage Area Edit Template
  description: Edit a BigQuery Storage Area on Google BigQuery
  tags:
    - edit
    - storage
    - bigquery
    - google
spec:
  owner: agile_lab
  useCaseTemplateId:
    - urn:dmb:utm:google-bigquery-storage-template:0.0.0
  parameters:
    - title: Update BigQuery Storage Area
      description: | 
        This wizard will allow you to edit the metadata for a previously created BigQuery Storage Area.
        
        Most metadata is editable but some (like the name, domain, system etc) are not; their fields will be read-only.
        
        Some of the files in the component's repository cannot be updated by this wizard, namely:
        - **Documentation**: `README.md`, `docs/index.md`, etc
        - **CI/CD**: `.gitlab-ci-yaml`
        You need to take care of updating these yourself, as given their nature it's hard to do automatically and they are often edited manually after the component's creation.
        
    - title: Update component metadata
      description: Update basic information for this component.
      required:
        - description
      properties:
        name:
          title: Name
          type: string
          description: Not editable. The name of the component.
          ui:disabled: true
        fullyQualifiedName:
          title: Fully Qualified Name
          type: string
          description: Component fully qualified name
        description:
          title: Description
          type: string
          description: Required. Help others understand what this component is for. What data will it contain?
        domain:
          title: Domain
          type: string
          description: Not editable. Domain of the System this component belongs to
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds: 
              - Domain
          ui:disabled: true
        parentRef:
          title: Parent
          type: string
          description: Not editable. Parent system this component belongs to
          ui:field: EntityPicker
          ui:filter:
            - fieldName: domain
              entityPath: spec.domain
          ui:options:
            allowArbitraryValues: false
            allowedKinds: 
              - System
          ui:disabled: true
        identifier:
          title: Identifier
          type: string
          description: Autogenerated from the information above. A unique identifier for the component. It will not be editable after creation and is a string composed of [a-zA-Z] separated by any of [-_].
          ui:disabled: true
        owner:
          title: Owner
          type: string
          description: Automatically selected from the System metadata. System owner.
          ui:field: EntitySelectionPicker
          ui:fieldName: parentRef
          ui:property: spec.owner
          ui:options:
            allowArbitraryValues: false
        dependsOn:
          title: Dependencies
          type: array
          description: |
            A component could depend on other components in the same System. This information will be used to deploy the components in such an order that their dependencies already exist.

            **Warning**: be careful not to select this component as its own dependency, otherwise it will become undeployable until you edit it again and remove that circular dependency.
          default: []
          items:
            type: string
            ui:field: EntityComponentsPicker
            ui:fieldName: parentRef
            ui:options:
              allowArbitraryValues: false
            relation: hasPart
        tags:
          title: Tags
          type: array
          description: Tags for the component
          default: []
          items:
            type: string

    - title: Update BigQuery table information
      description: |-
        Edit the information about the target project and dataset where the table Storage Area will be created,
        as well as the source table name. If no value is provided for the **dataset** field, an automatic value will
        be generated based on the domain, system name, major version, and deployment environment
      required:
        - project
        - tableName
      properties:
        project:
          title: Project ID
          type: string
          description: Google BigQuery project ID where the dataset is stored
        dataset:
          title: Dataset name
          type: string
          description: Dataset name where the source table is stored and the table table will be created. If not provided
            it will be autogenerated
          ui:disabled: true
        tableName:
          title: Table name
          type: string
          description: Table name to create in the specified dataset


    - title: Update Table schema
      description: |-
        Update the schema of the Storage Area table. Primitive data types supported.
        
        The **Table** schema specifies the structure of the data that will be exposed through the Storage Area.  
        
        This schema will be used by the Storage Area to edit a Google BigQuery table with the exact columns defined in this schema.
      properties:
        schemaDefinition:
          type: object
          ui:options:
            displayTitle: false
          properties:
            schemaColumns:
              title: Column Definitions
              type: array
              ui:ArrayFieldTemplate: ArrayTableTemplate
              items:
                type: object
                ui:ObjectFieldTemplate: TableRowTemplate
                required:
                  - name
                  - dataType
                properties:
                  name:
                    type: string
                    title: Name
                  description:
                    type: string
                    title: Description
                  dataType:
                    type: string
                    default: STRING
                    title: Data Type
                    enum:
                      - STRING
                      - INTEGER
                      - FLOAT
                      - NUMERIC
                      - BIGNUMERIC
                      - BOOLEAN
                      - TIMESTAMP
                      - DATE
                      - TIME
                      - DATETIME
                      - JSON
                      - GEOGRAPHY
                      - BYTES
                  constraint:
                    type: string
                    title: Mode
                    default: NULLABLE
                    enum:
                      - NULLABLE
                      - REQUIRED
                      - REPEATED
                allOf:
                  - if:
                      properties:
                        dataType:
                          oneOf:
                            - const: STRING
                            - const: BYTES
                    then:
                      properties:
                        dataLength:
                          title: Column Length
                          type: integer
                          description: Maximum length of column row
                          minimum: 0
                  - if:
                      properties:
                        dataType:
                          oneOf:
                            - const: NUMERIC
                            - const: BIGNUMERIC
                    then:
                      properties:
                        precision:
                          title: Precision
                          type: integer
                          description: Precision of the numeric data type
                          minimum: 1
                          maximum: 38
                          default: 38
                        scale:
                          title: Scale
                          type: integer
                          description: Scale of the numeric data type; cannot be greater than precision minus 1
                          minimum: 0
                          maximum: 38
                          default: 0
                        roundingMode:
                          title: Rounding mode
                          type: string
                          default: ROUNDING_MODE_UNSPECIFIED
                          enum:
                            - ROUNDING_MODE_UNSPECIFIED
                            - ROUND_HALF_AWAY_FROM_ZERO
                            - ROUND_HALF_EVEN    